### ISSUE TITLE
Confusion over types when upgrading to rust 1.54.0 and ndarray 0.15.0 - error[E0308]

### ISSUE THREAD

**Issue by iiSeymour** [rust-ndarray/ndarray#1064]
I'm trying to upgrade my library to build with rust 1.54.0 and ndarray 0.15.0 but I've got myself into a pickle ([build log](https://github.com/nanoporetech/fast-ctc-decode/runs/3495530905?check_suite_focus=true#step:4:139)).

```
   --> src/lib.rs:111:21
    |
111 |                     &network_output,
    |                     ^^^^^^^^^^^^^^^ expected struct `ArrayBase`, found struct `ndarray::ArrayBase`
    |
    = note: expected reference `&ArrayBase<ViewRepr<&f32>, Dim<[usize; 2]>>`
               found reference `&ndarray::ArrayBase<ndarray::ViewRepr<&f32>, ndarray::dimension::dim::Dim<[usize; 2]>>`
    = note: perhaps two different versions of crate `ndarray` are being used?
```

Cargo.toml:

```
[dependencies]
numpy = "0.14.1"
ndarray-stats = "0.5"
ndarray = { version = "0.15.0", features = ["blas", "serde"] }
pyo3 = { version = "0.14.4", features = ["extension-module"] }
```

Cargo tree:

```
$ cargo tree | grep ndarray
├── ndarray v0.15.3
├── ndarray-stats v0.5.0
│   ├── ndarray v0.15.3 (*)
│   ├── ndarray v0.14.0
```

I'm a little stuck so any help would be greatly appreciated.

**Comment by bluss** [comment]
It looks like the compiler's note might be correct - `note: perhaps two different versions of crate `ndarray` are being used?`

**Comment by iiSeymour** [comment]
Ah, it was staring me in the face the whole time - `cargo tree` shows the patch version of `.3` but I have pinned `.0` in the manifest 🤦🏻
