### ISSUE TITLE
Can't get BLAS support to work

### ISSUE THREAD

**Issue by RoberTnf** [rust-ndarray/ndarray#586]
After trying various solutions, I can't get BLAS to work on ndarray 0.12.1. I keep getting the error: `undefined reference to "cblas_ddot"`

### cargo.toml

```
[dependencies]
ndarray = { version = "0.12.1", features = ["blas"] }
blas-src = { version = "*", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.1", default-features = false, features = ["cblas", "system"] }
```

### main.rs
```
#[macro_use]
extern crate ndarray;

fn main() {
    let p1 = array![1., 0., 0.];
    let p2 = array![0., 0., 1.];
    println!("{}", p1.dot(&p2))
}
```
Using the solution from: https://github.com/rust-ndarray/ndarray/issues/251#issuecomment-292751938 works, but gives the same error when bumping ndarray to 0.12.1

I hope I didn't miss any obvious documentation!

**Comment by SuperFluffy** [comment]
Try and add `extern crate openblas_src;` to the top of your `main.rs`.
Reason is that cargo needs to explicitly link openblas with your library.

See the wiki of the rust blas GitHub organization.

**Comment by RoberTnf** [comment]
With: 
```
extern crate openblas_src;
#[macro_use]
extern crate ndarray;

fn main() {
    let p1 = array![1., 0., 0.];
    let p2 = array![0., 0., 1.];
    println!("{}", p1.dot(&p2))
}```

It's still not working, same error. 
You mean this page: https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki ? 
Thank you for your time!

**Comment by SuperFluffy** [comment]
I checked it on my end and everything works.

Since you explicitly configure and set `"system"` as a feature of `openblas_src`, are you sure you have it installed and available in your `LD_LIBRARY_PATH`?

**Comment by RoberTnf** [comment]
I'm on Arch Linux, with this packages:

```
cblas 3.8.0-2
openblas 0.3.5-1
```

`LD_LIBRARY_PATH` was not set up, but after making it point to `/usr/lib`, the command `$ ls $LD_LIBRARY_PATH | grep blas` outputs:
```
libblas.so
libblas.so.3
libcblas.so
libcblas.so.3
libcblas.so.3.8.0
libgslcblas.so
libgslcblas.so.0
libgslcblas.so.0.0.0
libopenblasp-r0.3.5.so
libopenblas.so
libopenblas.so.3
```

But the error still persists.

**Comment by RoberTnf** [comment]
Thank you, that does work!

**Comment by matzebond** [comment]
In Arch Linux the package `community/openblas` somehow does not include the `cblas_*` functions, which is why we get link errors on Arch Linux.
Currently I have to call `gcc -lopenblas -lcblas` to correctly link the `cblas_*` functions. It was mentioned that the `aur/openblas-lapack` works fine I did not test that yet and used openblas in ndarray without the `"system"` feature. 
In the future mdeff is proposing to correct this miss behavior in https://bugs.archlinux.org/task/66092 

Source:
https://bugs.archlinux.org/task/59046?project=5&string=openblas

**Comment by sethmnielsen** [comment]
Thanks, @matzebond! On Arch, I installed the `aur/openblas-lapack` package and everything is linking up great now. I did use the `"system"` feature.

**Comment by MartinRJDagleish** [comment]
@sethmnielsen Thank you the other version did also not work for me (using Arch Linux WSL on Win10) and only the installation of  `aur/openblas-lapack` and uninstall of previous `lapack` and `openblas` worked. 

I also used the `features = ["openblas-system"]` in the `Cargo.toml` for `ndarray-linalg`.

**Comment by grindingpeon** [comment]
@MartinRJDagleish @sethmnielsen thanks!

Can confirm on my end; the error still persists on Arch.
I also got the `undefined reference` error when having

```toml
[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module"]}
numpy = "0.24"
ndarray = { version = "0.16"}
ndarray-linalg = { version = "0.17", default-features = false, features = ["openblas-system"] }
```

in my `Cargo.toml`.

Running

```bash
❯ yay -S openblas-lapack
Sync Explicit (1): blas-openblas-0.3.30-1
[sudo] password for jsr-p:
resolving dependencies...
looking for conflicting packages...
:: blas-openblas-0.3.30-1 and blas-3.12.1-2 are in conflict. Remove blas? [y/N] y
:: blas-openblas-0.3.30-1 and cblas-3.12.1-2 are in conflict. Remove cblas? [y/N] y
:: blas-openblas-0.3.30-1 and lapack-3.12.1-2 are in conflict. Remove lapack? [y/N] y

Packages (4) blas-3.12.1-2  cblas-3.12.1-2  lapack-3.12.1-2  blas-openblas-0.3.30-1
❯ uname -r
6.15.2-arch1-1
```

it now works i.e. installing the [AUR package](https://aur.archlinux.org/packages/openblas-lapack)
also solved it for me.

**Comment by grindingpeon** [comment]
@MartinRJDagleish @sethmnielsen  thanks!

Can confirm on my end; the error still persists on Arch.
I also got the `undefined reference` error when having

```toml
[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module"]}
numpy = "0.24"
ndarray = { version = "0.16"}
ndarray-linalg = { version = "0.17", default-features = false, features = ["openblas-system"] }
```

in my `Cargo.toml`.

Running

```bash
❯ yay -S openblas-lapack
Sync Explicit (1): blas-openblas-0.3.30-1
resolving dependencies...
looking for conflicting packages...
:: blas-openblas-0.3.30-1 and blas-3.12.1-2 are in conflict. Remove blas? [y/N] y
:: blas-openblas-0.3.30-1 and cblas-3.12.1-2 are in conflict. Remove cblas? [y/N] y
:: blas-openblas-0.3.30-1 and lapack-3.12.1-2 are in conflict. Remove lapack? [y/N] y

Packages (4) blas-3.12.1-2  cblas-3.12.1-2  lapack-3.12.1-2  blas-openblas-0.3.30-1
❯ uname -r
6.15.2-arch1-1
```

it now works i.e. installing the [AUR package](https://aur.archlinux.org/packages/openblas-lapack)
also solved it for me.
